# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: deploy book

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.12

    - name: Install pdm
      run: |
        pip install pdm

    - name: Install dependencies
      run: |
        pdm install

    # Build the book
    - name: Build the book
      run: |
        pdm run jupyter-book build ./docs/

    # publish
#     - name: Upload artifact
#       uses: actions/upload-pages-artifact@v1
#       with:
#         # Upload entire repository
#         path: './docs/_build/html/'
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        # Upload entire repository
        path: './docs/_build/html/'
    - name: Deploy to GitHub Pages
      id: publish
      uses: actions/deploy-pages@v2
